[package]
name = "mytwm"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "mytwm"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.75"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter", "json"] }
penrose = { path = "../penrose/" }
